services:
  mongo:
    image: mongo:8.0
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: "no"

  server:
    build: ./server
    container_name: ${SERVER_CONTAINER_NAME}
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "${SERVER_PORT}:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
    restart: "no"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ${CLIENT_CONTAINER_NAME}
    command: npm start
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: "no"

volumes:
  mongo-data:
