services:
  mongo:
    image: mongo:8.0
    container_name: docker_template_database
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  server:
    build: ./server
    container_name: docker_template_server
    ports:
      - "${SERVER_PORT}:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
  client:
    build: ./client
    container_name: docker_template_client
    ports:
      - "${CLIENT_PORT}:80"

volumes:
  mongo-data:
