services:
  mongo:
    image: mongo:8.0
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  server:
    build: ./server
    container_name: ${SERVER_CONTAINER_NAME}
    ports:
      - "${SERVER_PORT}:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
  client:
    build: ./client
    container_name: ${CLIENT_CONTAINER_NAME}
    ports:
      - "${CLIENT_PORT}:80"

volumes:
  mongo-data:
