services:
  mongo:
    image: mongo:8.0
    container_name: docker_template_database
    ports:
      - "1919:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  server:
    build: ./server
    container_name: docker_template_server
    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5678:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:examplepassword@docker_template_database:27017/mydb?authSource=admin
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: docker_template_client
    command: npm start
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "1234:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:
